import { Registry } from "@/registry/schema"

export const ui: Registry = [
  {
    name: "skiper-card",
    registryDependencies: ["badge"],
    type: "registry:ui",
    dependencies: ["motion", "react-wrap-balancer"],
    files: ["ui/skiper-card.tsx"],
  },
  {
    name: "skiper-marquee",
    type: "registry:ui",
    dependencies: ["framer-motion"],
    files: ["ui/skiper-marquee.tsx"],
  },
  {
    name: "animated-number-countdown",
    type: "registry:ui",
    dependencies: ["framer-motion", "@number-flow/react"],
    files: ["ui/animated-number-countdown.tsx"],
  },
  {
    name: "animated-number-counter",
    type: "registry:ui",
    dependencies: ["framer-motion", "@number-flow/react"],
    files: ["ui/animated-number-counter.tsx"],
  },
  {
    name: "animated-number-random",
    type: "registry:ui",
    dependencies: ["framer-motion", "@number-flow/react"],
    files: ["ui/animated-number-random.tsx"],
  },
  {
    name: "card-carousel",
    registryDependencies: ["badge"],
    type: "registry:ui",
    dependencies: ["framer-motion", "@number-flow/react", "swiper"],
    files: ["ui/card-carousel.tsx"],
  },
  {
    name: "card-swipe",
    registryDependencies: ["badge"],
    type: "registry:ui",
    dependencies: ["framer-motion ", "swiper"],
    files: ["ui/card-swipe.tsx"],
  },
  {
    name: "stacked-dialog",
    registryDependencies: ["avatar"],
    type: "registry:ui",
    dependencies: ["framer-motion ","@radix-ui/react-portal"],
    files: ["ui/stacked-dialog.tsx"],
  },
  {
    name: "minimal-card",
    type: "registry:ui",
    dependencies: ["framer-motion "],
    files: ["ui/minimal-card.tsx"],
  },
  {
    name: "blur-vignette",
    type: "registry:ui",
    dependencies: ["framer-motion "],
    files: ["ui/blur-vignette.tsx"],
  },
  {
    name: "masked-div",
    type: "registry:ui",
    dependencies: ["framer-motion "],
    files: ["ui/masked-div.tsx"],
  },
  {
    name: "expandable",
    type: "registry:ui",
    dependencies: ["framer-motion"],
    files: ["ui/expandable.tsx"],
  },
  {
    name: "image-cursortrail",
    type: "registry:ui",
    dependencies: ["framer-motion"],
    files: ["ui/image-cursortrail.tsx"],
  },
  {
    name: "hover-expand",
    type: "registry:ui",
    dependencies: ["framer-motion"],
    files: ["ui/hover-expand.tsx"],
  },
  {
    name: "text-effect-flipper",
    type: "registry:ui",
    dependencies: ["framer-motion"],
    files: ["ui/text-effect-flipper.tsx"],
  },
  {
    name: "slide-button",
    type: "registry:ui",
    dependencies: ["framer-motion"],
    files: ["ui/slide-button.tsx"],
  },
  {
    name: "share-button",
    type: "registry:ui",
    dependencies: ["framer-motion"],
    files: ["ui/share-button.tsx"],
  },
  {
    name: "badge-button",
    type: "registry:ui",
    dependencies: ["framer-motion"],
    files: ["ui/badge-button.tsx"],
  },
  {
    name: "text-scroll",
    type: "registry:ui",
    dependencies: ["framer-motion"],
    files: ["ui/text-scroll.tsx"],
  },
  {
    name: "image-ripple",
    type: "registry:ui",
    dependencies: ["framer-motion"],
    files: ["ui/image-ripple.tsx"],
  },
  {
    name: "expanded-tabs",
    type: "registry:ui",
    dependencies: ["framer-motion", "usehooks-ts", "lucide-react"],
    files: ["ui/expanded-tabs.tsx"],
  },
]
