// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "animated-number": {
      name: "animated-number",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/animated-number")),
      source: "",
      files: ["registry/default/ui/animated-number.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "card-carousel": {
      name: "card-carousel",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/card-carousel")),
      source: "",
      files: ["registry/default/ui/card-carousel.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "animated-number-demo": {
      name: "animated-number-demo",
      type: "components:example",
      registryDependencies: ["animated-number"],
      component: React.lazy(() => import("@/registry/default/example/animated-number-demo")),
      source: "",
      files: ["registry/default/example/animated-number-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "card-carousel-demo": {
      name: "card-carousel-demo",
      type: "components:example",
      registryDependencies: ["card-carousel-demo"],
      component: React.lazy(() => import("@/registry/default/example/card-carousel-demo")),
      source: "",
      files: ["registry/default/example/card-carousel-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "authentication-01": {
      name: "authentication-01",
      type: "components:block",
      registryDependencies: ["button","card","input","label"],
      component: React.lazy(() => import("@/registry/default/block/authentication-01")),
      source: "__registry__/default/block/authentication-01.tsx",
      files: ["registry/default/block/authentication-01.tsx"],
      category: "Authentication",
      subcategory: "Login",
      chunks: []
    },
  },
}
