// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "animated-number-countdown": {
      name: "animated-number-countdown",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/animated-number-countdown")),
      source: "",
      files: ["registry/default/ui/animated-number-countdown.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "animated-number-counter": {
      name: "animated-number-counter",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/animated-number-counter")),
      source: "",
      files: ["registry/default/ui/animated-number-counter.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "animated-number-random": {
      name: "animated-number-random",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/animated-number-random")),
      source: "",
      files: ["registry/default/ui/animated-number-random.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "card-carousel": {
      name: "card-carousel",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/card-carousel")),
      source: "",
      files: ["registry/default/ui/card-carousel.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "stacked-dialog": {
      name: "stacked-dialog",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/stacked-dialog")),
      source: "",
      files: ["registry/default/ui/stacked-dialog.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "minimal-card": {
      name: "minimal-card",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/minimal-card")),
      source: "",
      files: ["registry/default/ui/minimal-card.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "blur-vignette": {
      name: "blur-vignette",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/blur-vignette")),
      source: "",
      files: ["registry/default/ui/blur-vignette.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "masked-div": {
      name: "masked-div",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/masked-div")),
      source: "",
      files: ["registry/default/ui/masked-div.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "expandable": {
      name: "expandable",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/expandable")),
      source: "",
      files: ["registry/default/ui/expandable.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "animated-number-countdown-demo": {
      name: "animated-number-countdown-demo",
      type: "components:example",
      registryDependencies: ["animated-number-countdown"],
      component: React.lazy(() => import("@/registry/default/example/animated-number-countdown-demo")),
      source: "",
      files: ["registry/default/example/animated-number-countdown-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "animated-number-counter-demo": {
      name: "animated-number-counter-demo",
      type: "components:example",
      registryDependencies: ["animated-number-counter"],
      component: React.lazy(() => import("@/registry/default/example/animated-number-counter-demo")),
      source: "",
      files: ["registry/default/example/animated-number-counter-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "animated-number-random-demo": {
      name: "animated-number-random-demo",
      type: "components:example",
      registryDependencies: ["animated-number-random"],
      component: React.lazy(() => import("@/registry/default/example/animated-number-random-demo")),
      source: "",
      files: ["registry/default/example/animated-number-random-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "card-carousel-demo": {
      name: "card-carousel-demo",
      type: "components:example",
      registryDependencies: ["card-carousel-demo"],
      component: React.lazy(() => import("@/registry/default/example/card-carousel-demo")),
      source: "",
      files: ["registry/default/example/card-carousel-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "stacked-dialog-demo": {
      name: "stacked-dialog-demo",
      type: "components:example",
      registryDependencies: ["stacked-dialog-demo"],
      component: React.lazy(() => import("@/registry/default/example/stacked-dialog-demo")),
      source: "",
      files: ["registry/default/example/stacked-dialog-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "minimal-card-demo": {
      name: "minimal-card-demo",
      type: "components:example",
      registryDependencies: ["minimal-card-demo"],
      component: React.lazy(() => import("@/registry/default/example/minimal-card-demo")),
      source: "",
      files: ["registry/default/example/minimal-card-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "blur-vignette-demo": {
      name: "blur-vignette-demo",
      type: "components:example",
      registryDependencies: ["blur-vignette-demo"],
      component: React.lazy(() => import("@/registry/default/example/blur-vignette-demo")),
      source: "",
      files: ["registry/default/example/blur-vignette-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "masked-div-demo": {
      name: "masked-div-demo",
      type: "components:example",
      registryDependencies: ["masked-div-demo"],
      component: React.lazy(() => import("@/registry/default/example/masked-div-demo")),
      source: "",
      files: ["registry/default/example/masked-div-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "expandable-demo": {
      name: "expandable-demo",
      type: "components:example",
      registryDependencies: ["expandable"],
      component: React.lazy(() => import("@/registry/default/example/expandable-demo")),
      source: "",
      files: ["registry/default/example/expandable-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "authentication-01": {
      name: "authentication-01",
      type: "components:block",
      registryDependencies: ["button","card","input","label"],
      component: React.lazy(() => import("@/registry/default/block/authentication-01")),
      source: "__registry__/default/block/authentication-01.tsx",
      files: ["registry/default/block/authentication-01.tsx"],
      category: "Authentication",
      subcategory: "Login",
      chunks: []
    },
  },
}
